### ISSUE TITLE
Match version number

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/Deno.jl#1]
Can we make the version number of this package match the version number of the deno binary that it provides? (NodeJS.jl does not do this unfortunately)

**Comment by Pangoraw** [comment]
There are no particular reason not to, we can use the same versioning as [JuliaPluto/DenoBuilder](https://github.com/JuliaPluto/DenoBuilder/releases) which is "$deno_version-$build_number". The build number is just in case the julia package needs to be updated and there is no new deno version.

**Comment by fonsp** [comment]
Ah I see, but you are only allowed to register `x.y.z` versions on the General registry... And I do see some reasons why we would want to release a patch for the same deno version. In that case let's just not do it.

**Comment by Pangoraw** [comment]
FYI, since NodeJS.jl is being moved to a JLL package, Deno_jll has been too. The code is in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/tree/master/D/Deno) and can be used like this:
 
```julia
(@v1.6) pkg> add Deno_jll
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [04572ae6] + Deno_jll v1.9.2+0
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [04572ae6] + Deno_jll v1.9.2+0
Precompiling project...
  62 dependencies successfully precompiled in 105 seconds (132 already precompiled, 1 skipped during auto due to previous errors)

julia> using Deno_jll
[ Info: Precompiling Deno_jll [04572ae6-984a-583e-9378-9577a1c2574d]

julia> deno() do exe
           run(`$exe`)
       end
Deno 1.9.2
exit using ctrl+d or close()
> 
```
