### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by Pangoraw** [JuliaPluto/Deno.jl#2]
As per the registry guidelines, the package name must be at least 5 characters long:
![image](https://user-images.githubusercontent.com/9824244/116660700-ae085380-a993-11eb-91e6-1a3d3aef45a4.png)

Should we rename the package to something like `DenoJS.jl` ?

**Comment by fonsp** [comment]
You closed this but we should rename it to DenoJS.jl right? Or we get permission to skip the rule, like JSON.jl.

Though, unline node, deno is never called "deno js", and it also a TS runtime..... hmm

**Comment by Pangoraw** [comment]
I was advised to release it as a _jll package since NodeJS.jl is moving to a _jll as well :smiley: . See [Deno_jll.jl](https://github.com/JuliaBinaryWrappers/Deno_jll.jl), the source for generating the package are located in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/blob/master/D/Deno/build_tarballs.jl) I don't think there is much value in keeping a thin wrapper around the jll package, what do you think?

```julia
(@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_tKnHUh/Project.toml`

(jl_tKnHUh) pkg> add Deno_jll@1.10.1
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `/tmp/jl_tKnHUh/Project.toml`
  [04572ae6] + Deno_jll v1.10.1+0
    Updating `/tmp/jl_tKnHUh/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.3.0
  ...
  [3f19e933] + p7zip_jll

julia> using Deno_jll

julia> deno() do exe
           run(`$exe`)
       end
Deno 1.10.1
exit using ctrl+d or close()
>

```
